# Generated by Django 5.0.3 on 2024-03-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default=None, max_length=100, null=True, verbose_name="제목"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "author",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="작성자"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
            ],
        ),
    ]
