# Generated by Django 5.0.3 on 2024-03-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(
                default=None, max_length=30, null=True, verbose_name="작성자"
            ),
        ),
    ]
