# Generated by Django 5.0.3 on 2024-03-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(
                default=None, max_length=100, null=True, verbose_name="제목"
            ),
        ),
    ]
